"""add_client_user_relationship

Revision ID: 758f8d00eac7
Revises: e4dbd8f00bad
Create Date: 2025-01-16 19:02:30.303670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758f8d00eac7'
down_revision: Union[str, None] = 'e4dbd8f00bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###
